language: php
php:
  - 5.5
  - 5.4
  - hhvm
install:
  - composer install
script:
  - vendor/bin/phpspec run
matrix:
  fast_finish: true
notifications:
  irc: 
    channels:
      - "irc.freenode.net#opengov_private"
    on_success: always
    on_failure: always
